name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 18.1.20+31

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.2.0
  country_picker: ^2.0.26
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  talker_dio_logger: ^4.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
